#!/usr/bin/env node
/**
 * llms-full.txt: el texto de todas las páginas públicas, en markdown, en un
 * solo fichero. Complementa a llms.txt (el índice con los datos clave): un
 * modelo que quiera la respuesta entera la lee de una vez, sin recorrer 40
 * páginas de HTML.
 *
 *   node tools/sitio/llms-full.js              → comprobar (falla si hay desfase)
 *   node tools/sitio/llms-full.js --escribir   → regenerarlo
 *
 * Sale del HTML publicado (no de los ficheros de datos), así que dice
 * exactamente lo que dice la web. Primero inglés, luego español.
 */
const fs = require('fs');
const path = require('path');

const R = path.join(__dirname, '..', '..');
const DOMINIO = 'https://hachi.live';
const escribir = process.argv.includes('--escribir');
const FUERA = /(privacy-policy|terms-of-service|data-deletion)\.html$/;

const ENTIDADES = { '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&#39;': "'", '&nbsp;': ' ',
  '&bull;': '•', '&rarr;': '→', '&mdash;': '—', '&ndash;': '–', '&euro;': '€', '&hellip;': '…', '&copy;': '©' };

function aMarkdown(html) {
  let b = (html.split(/<body[^>]*>/)[1] || '').split('</body>')[0];
  b = b.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<svg[\s\S]*?<\/svg>|<noscript[\s\S]*?<\/noscript>/g, '')
    .replace(/<nav\b[\s\S]*?<\/nav>/g, '')               // menús, migas, índices
    .replace(/<footer\b[\s\S]*?<\/footer>/g, '')
    .replace(/<form\b[\s\S]*?<\/form>/g, '')
    .replace(/<div class="escena"[\s\S]*?<\/section>/, '</section>')   // la maqueta del hero
    .replace(/<h1[^>]*>/g, '\n\n# ').replace(/<h2[^>]*>/g, '\n\n## ')
    .replace(/<h3[^>]*>/g, '\n\n### ').replace(/<h4[^>]*>/g, '\n\n#### ')
    .replace(/<\/h[1-4]>/g, '\n')
    .replace(/<summary[^>]*>/g, '\n\n### ').replace(/<\/summary>/g, '\n')
    .replace(/<li[^>]*>/g, '\n- ')
    .replace(/<t[dh][^>]*>/g, ' | ').replace(/<\/tr>/g, '\n')
    .replace(/<br\s*\/?>/g, '\n')
    .replace(/<\/(p|div|section|article|ul|ol|table|details|header)>/g, '\n\n')
    .replace(/<[^>]+>/g, '');
  b = b.replace(/&[a-z#0-9]+;/g, (e) => ENTIDADES[e] || e);
  return b.split('\n').map((l) => l.replace(/[ \t]+/g, ' ').trim()).join('\n')
    .replace(/\n{3,}/g, '\n\n').replace(/\n\n- /g, '\n- ').trim();
}

const sitemap = fs.readFileSync(path.join(R, 'sitemap.xml'), 'utf8');
const urls = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
const fichero = (u) => { const p = u.replace(DOMINIO + '/', ''); return p === '' || p.endsWith('/') ? p + 'index.html' : p; };
const paginas = urls.map((u) => ({ u, p: fichero(u) }))
  .filter(({ p }) => !FUERA.test(p) && fs.existsSync(path.join(R, p)))
  .map(({ u, p }) => {
    const h = fs.readFileSync(path.join(R, p), 'utf8');
    return { u, lang: (h.match(/<html lang="([a-z]+)"/) || [])[1] || 'en',
      titulo: (h.match(/<title>([^<]+)<\/title>/) || [])[1] || p, md: aMarkdown(h) };
  });
// Orden: portada, luego el resto por URL; inglés antes que español.
const orden = (a) => (a.lang === 'en' ? 0 : 1) * 1000 + (/\/(es\/)?$/.test(a.u) ? 0 : 1);
paginas.sort((a, b) => orden(a) - orden(b) || a.u.localeCompare(b.u));

function generar() {
  return `# Hachi · full site content

> Every public page of https://hachi.live as plain markdown, English first and
> then Spanish. The short index with the key facts (prices by market, plans,
> guardrails, notes for AI assistants) is https://hachi.live/llms.txt. Where
> they differ, llms.txt is authoritative.
>
> Generated by tools/sitio/llms-full.js from the published HTML.

${paginas.map((x) => `\n---\n\nSource: ${x.u}\nLanguage: ${x.lang}\nTitle: ${x.titulo}\n\n${x.md}\n`).join('')}`;
}

if (escribir) {
  const t = generar();
  fs.writeFileSync(path.join(R, 'llms-full.txt'), t);
  console.log('llms-full.txt regenerado · ' + paginas.length + ' páginas · ' + Math.round(t.length / 1024) + ' KB');
  process.exit(0);
}
const actual = fs.existsSync(path.join(R, 'llms-full.txt')) ? fs.readFileSync(path.join(R, 'llms-full.txt'), 'utf8') : '';
if (actual === generar()) { console.log('✅ llms-full.txt al día · ' + paginas.length + ' páginas'); process.exit(0); }
console.log('✗ llms-full.txt desfasado → node tools/sitio/llms-full.js --escribir'); process.exit(1);
